- macros/src/main/scala/gestalt/macros/Annotations.scala
- macros/src/test/scala/gestalt/macros/MacrosTest.scala
- src/main/scala/gestalt/dotty/Expander.scala
Added DottyToolbox to the arguments. The two simple macros (`plus.apply` and `plusObject.apply`) now work properly.
> Def macros : added missing DottyToolbox argument

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/main/scala/packaged/macros/InnerClassMacro.scala
- macros/src/main/scala/packaged/macros/InnerObjectMacro.scala
- macros/src/main/scala/packaged/macros/PackagedImplicits.scala
- macros/src/main/scala/packaged/macros/package.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/dotty/Expander.scala
- Added tests for applying macros on different prefixes: method calls(with and without arguments), method calls on generic types, constructors.
- ~~Using `info.resultType`, because when the prefix applies a function with arguments, info is a `Method` type which gives a class of `<none>`. In other cases both yield the same class.~~
- Using `Select.symbol.owner` to get the owner of the method. This replaces `info` which gives `<none>` when prefix applies a function with arguments.
- Added macros defined inside packages, outside, inside objects. Created tests applying these macros.
- Added method `javaClassName`. We cannot use `fullName` as the java class name splits inner classes/objects with a dot `.` while java uses `$`.
- Both things needed to be fixed for …
> Def macros: Implicit class support

- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/dotty/Expander.scala
Using the static methods introduced by @liufengyun  ['s changes](https://github.com/liufengyun/dotty/commit/43fdbf1e3df3e999acb14e3e32c0980e7280083b) instead of object methods (calls on the `MODULE$` field). 
These calls caused problems because the `MODULE$` field was not generating for objects and classes inside other classes. See  #13
> Def macros: Inner class support

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
Enabled the tests, the fix is in liufengyun/dotty#1 , fails until the dotty library is updated
> Def macros: tests for type parameters

- macros/src/main/scala/gestalt/macros/Annotations.scala
- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/AnnotationMacroTest.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/dotty/Expander.scala
-  Fix for #16 : Added `enclosingPosition` to DottyToolbox populating it in both expansion of quasiquotes as well as def and annotation macros. So it won't fail when writing the macro nor when it is expanded. Added `.withPos` to all AST elements.
Initially I added the `.withPos` to only leaf nodes ( @liufengyun, as you suggested). However there were a lot of both leaves, and non-leaves, and it was hard in cases to tell whether a node could be a leaf (is any of Option[Tree] non-empty). To avoid reduce complexity and avoid confusion, I added `.withPos` to all AST elements.
- Fix for #17 : In `Quote.lift` literal now generates the code of creating the literal not the literal itself.
- Also added "meta-types" to all the methods and vals. 
If Trees had a type parameter that should the type of …
> Quasiquotes: fix for "hole-free" and literals

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/dotty/Expander.scala
- Added a test macro of adding BigInt methods to String. It also compresses the representation string to the highest possible radix to save constant size.
- Handling the case where prefix is not specified. Passing a `prefix=null` in this case.
- Added a warning when def macros fails to expand for easier debugging.
> Def macros: support for implicit def

- macros/src/test/scala/gestalt/macros/Driver.scala
- macros/src/test/scala/gestalt/macros/QuasiquoteTest.scala
I've moved quasiquote test to the outer project before (probably after a drink), it does't make any sense, as the outer project is compiled by scalac instead of modified version of dotty.
> move quasiquote test to macro project

- macros/src/main/scala/gestalt/macros/Annotations.scala
- macros/src/main/scala/gestalt/macros/Quasiquotes.scala
- macros/src/test/scala/gestalt/macros/QuasiquoteTest.scala
- src/main/scala/gestalt/Quasiquote.scala
- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/dotty/Expander.scala
- src/main/scala/gestalt/package.scala
Now the split is done and the test set pass -- except one cheat to change the definition of one annotation macro in order for it to compile. I think it's possible to do better without the cheat, I'll improve tomorrow.
Modifiers are refactored completely, they are no longer trees. The usage of modifiers for macro writers will be much simpler.
Review @valdisxp1 .
> Split toolbox to StructToolbox and TypeToolbox

- macros/src/main/scala/gestalt/macros/Annotations.scala
- macros/src/test/scala/gestalt/macros/AnnotationMacroTest.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- added test for adding private, protected and public defs.
- fixed issue with `private[this]` and `protected[this]`. Previously it was failing in the Namer with "no enclosing class or object is named this". The issue would only appear when the macro is actually expanded and reaches the Typer.
#26
> Quasiquotes: fix private and protected mods

- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
Previously we do conversion of modifiers, which is against our philosophy of avoiding conversions. This PR refactor the code to be consistent with the overall design.
Review @valdisxp1 .
> avoid conversion of modifiers

- build.sbt
- project/plugins.sbt
Add assembly plugin so that it's possible to run `sbt assembly` to create bundled jars.
The jars can in turn passed to our dotc to compile macros in command line.
```
./bin/dotc -cp gestalt-assembly-0.1.1.jar   macro.scala
```
> add assembly plugin

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- Added `Ascribe` to `TypedToolbox`. For some reason **every** argument for varargs is wrapped in in an ascription. Need to extract from it to do anything.
- Added `SeqLiteral` to `TypedToolbox`. The varargs can be either a collection or a sequence literal, therefore macro implementation always gets it as a single argument. 
The only other alternative I can think of is to look at `(... 1,3,4,5)` as `Seq[Int].apply(1,3,4,5)` similar to what Java does with arrays and their varargs. Then items could be extracted with `Apply`, `TypeApply` and `Ident`. This looked like too much magic to me.
- Added a special case to `Apply` extractor to handle varargs. 
- Tests for all three cases.
> Def macros: varargs

- build.sbt
- macros/src/main/scala/gestalt/macros/DefMacros.scala
- src/main/scala/gestalt/Quasiquote.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
remove the accidental complexity with varargs, now the macro writers either get a SeqLiteral tree, or a `Typed` tree, which is more regular.
> Fix #38: remove the accidental complexity with varargs

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/main/scala/gestalt/macros/TypeToolbox.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- macros/src/test/scala/gestalt/macros/Driver.scala
- macros/src/test/scala/gestalt/macros/TypeToolboxTest.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
Fix #48: Implement first set of semantic APIs.
- The semantic APIs are _mostly_ driven by macro use cases
- The semantic APIs minimises assumptions on compiler internals
- Instead of the concept `Symbol`, we find `Member` is more understandable
```Scala
/** are the two types equal? */
def =:=(tp1: Type, tp2: Type): Boolean
/** is `tp1` a subtype of `tp2` */
def <:<(tp1: Type, tp2: Type): Boolean
/** returning a type referring to a type definition */
def typeRef(path: String): Type
/** returning a type referring to a value definition */
def termRef(path: String): Type
/** type associated with the tree */
def typeOf(tree: Tree): Type
/** does the type refer to a case class? */
def isCaseClass(tp: Type): Boolean
/** val fields of a case class Type -- only the ones declared in primary …
```
> fix #48: implement and test initial semantic API

- build.sbt
- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/QuasiquoteTest.scala
- macros/src/test/scala/gestalt/macros/TypeToolboxTest.scala
- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
Refactoring of toolbox:
- define more abstract type members for safety by construction
- define more extractors for expressions
- define representors for definition trees -- which is recommended over extractors
- merge `ValDef` with `VarDef` and add `Mutable` flag
- remove `PrimaryCtor`
- add flags `ValParam` and `VarParam` as in scala.meta
> Refactor of toolbox

- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
refactor to use extension methods on abstract type.
This PR doesn't affect API, except `For` and `Import`, where it's grouped.
> refactor to use extension methods on abstract type

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/dotty/Expander.scala
The multi-param block support is fixed in https://github.com/liufengyun/dotty/commit/b2a85c4e4b350eae82d135fc62aae99684085b0c. The commit also refactor macro expansion to minimise changes to the compiler core.
> support multi-param blocks

- macros/src/main/scala/gestalt/macros/TypeToolbox.scala
- macros/src/test/scala/gestalt/macros/TypeToolboxTest.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/TypeTag.scala
- src/main/scala/gestalt/Types.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/dotty/Expander.scala
Fix #60: Together with following commit, this implements compile-time WeakTypeTag.
https://github.com/liufengyun/dotty/commit/f32b71f11c5794e21c1930b4ff873b71b64fbc27
> Fix #60 :support WeakTypeTag

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/main/scala/gestalt/macros/TypeToolbox.scala
- macros/src/test/scala/gestalt/macros/TypeToolboxTest.scala
- src/main/scala/gestalt/Denotations.scala
- src/main/scala/gestalt/Symbols.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/Types.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
I'm pretty receptive to the concept `Denotation`, I think it provides better experience to deal with path-dependent types.
This PR wraps type operations as extension methods.
> Prefer denotations over symbols in the API

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/main/scala/gestalt/macros/Monadless.scala
- macros/src/main/scala/gestalt/macros/TypeToolbox.scala
- macros/src/test/scala/gestalt/macros/Driver.scala
- macros/src/test/scala/gestalt/macros/MonadlessOptionTest.scala
- macros/src/test/scala/gestalt/macros/TypeToolboxTest.scala
- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/Toolbox.scala
- src/main/scala/gestalt/Trees.scala
- src/main/scala/gestalt/Types.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/dotty/Expander.scala
This is an example implementation of a subset of `Monadless` in gestalt, the tests pass.
A list of additions in semantic API:
- add `WeakTypeTag`
- add `TypedSplice`
- add `Type.companion`, `Type.widen` and `Type.denot`
- add extractor and API for `MethodType`
- add extractor for `ByNameType`
Some findings or changes:
- Two bugs of scala.meta quasiquotes
- Fix one bug about `UntypedTreeMap` in Dotty
- Synthesise `prefix` if it's `null` for def macros
- Todo: missing auto lifting from String to identifier makes `quasiquote` inconvenient
- Fix bug in quasiquote lifting of ValDefs
> Monadless test case

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/Trees.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
* Fixed MatchError when expending quasiquotes by matching on `m.Term.ApplyType`, not `m.Type.Apply`. This is what the meta parser gives us.
* Fixed "toolbox.Ident does not have a `::` method" exception. Using `list.::(item)` 
* Now it is possible to splice in typeTrees in quasiquotes. Always wrapping the value in an `Some` if it expects an `Option`.
* Fixed Match error in Namer:863 and "Iterator does not take type arguments". Namer and Typer expect the parent to be a type not a term. Using `name.toTypeName` instead of `name.toTermName`
* Fixed MatchError when expending quasiquotes by handling the forth case (qualifier present, no type parameter).
* Added tests for all of these cases.
This is essential for JSON macros #41
> Fix anonymous class creation

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
Fixed partial function creation by using the `d.EmptyTree` singleton value. The Typer was failing when using `d.Thicket(Nil)`.
> Fix partial function creation

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/Quote.scala
- src/main/scala/gestalt/Trees.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
A new instance is created by applying the constructor method `<init>` to the arguments, not by calling `New` on the type applied to the arguments. I found this out by running the parser on `new Some[Int](3)`, i.e. a modified version of `dotty/tools/dotc/parsing/parseFile.scala`.
* Created a new constructor `NewInstance`
* Combined `New` and `AnonymClass` into `NewAnonymClass` as discussed in #73 
* Refactor: decomposed `liftInitCall` into multiple always successful, private extractors. This way we do not have to have 2^n cases in a match statement. Reused the same extractors for `liftNewInstance`
* Added tests for new instance creation
Necessary fix for JSON deserialization #41
> Fix new instance creation

- macros/src/main/scala/gestalt/macros/Optional.scala
- macros/src/test/scala/gestalt/macros/Driver.scala
- macros/src/test/scala/gestalt/macros/OptionalTest.scala
- src/main/scala/gestalt/Symbols.scala
- src/main/scala/gestalt/Trees.scala
- src/main/scala/gestalt/Types.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
Implementation of the Optional macro:
https://github.com/scalamacros/macrology201/blob/part1/macros/src/main/scala/Macros.scala
> Implementation of the Optional macro

- macros/src/main/scala/gestalt/macros/Annotations.scala
- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/main/scala/gestalt/macros/Monadless.scala
- macros/src/main/scala/gestalt/macros/Optional.scala
- macros/src/main/scala/gestalt/macros/Quasiquotes.scala
- macros/src/main/scala/gestalt/macros/TypeToolbox.scala
- src/main/scala/gestalt/api.scala
- src/main/scala/gestalt/core/Symbols.scala
- src/main/scala/gestalt/core/Trees.scala
- src/main/scala/gestalt/core/Types.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/options.scala
- src/main/scala/gestalt/quasiquotes/Quote.scala
This is a simple while practical solution to the hygiene problem: it still allows programmers to do the hack if `scala.gestalt.options.unsafe` is imported. By default, only fully-qualified name or symbol-based name is supported.
When scala supports literal types, we can do better with the API:
```Scala
def Ident(name: "_root_"): Tree
def Ident(name: "scala")(implcit dummy: C): Tree
```
> a simple solution to hygiene problem

- macros/src/main/scala/gestalt/macros/Monadless.scala
- src/main/scala/gestalt/api.scala
- src/main/scala/gestalt/core/Trees.scala
- src/main/scala/gestalt/core/Types.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
The `infer` API is needed for the JsonMacro refactoring.
> add Infer as API

- macros/src/main/scala/gestalt/macros/Quasiquotes.scala
- src/main/scala/gestalt/api.scala
- src/main/scala/gestalt/core/Toolbox.scala
- src/main/scala/gestalt/core/Trees.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/quasiquotes/Quote.scala
@valdisxp1 I did the refactoring for `InitCall`. It will be much easier for you to refactor `NewInstance` based on this PR.
The most important motivation for making `qual`, `name`, `targs` explicit
in the constructor is to make the extractor more friendly. The
consideration for semantic difference is secondary.
I'd like to abandon the original design due to following reasons:
- inspecting syntactic structure of New expression is useless, only  crappy macros do that
- even if we merge `qual`, `name` and `targs`, it's still not difficult to address
potential semantic difference in compiler implementation.
- following code is valid in Scala, which implies the semantic consideration is not well founded.
```Scala
type A = Some[Int]
new A(3)
```
> refactor design of InitCall

- macros/src/main/scala/gestalt/macros/Optional.scala
- macros/src/main/scala/gestalt/macros/Quasiquotes.scala
- src/main/scala/gestalt/api.scala
- src/main/scala/gestalt/core/Toolbox.scala
- src/main/scala/gestalt/core/Trees.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
- src/main/scala/gestalt/quasiquotes/Quote.scala
1. Added a `NewInstance` constructor that respects macro hygiene (safe) as per @liufengyun 's example.
2. Made the syntactic way of calling `NewInstance` unsafe. Even if you provide a qualifier, it may not be fully qualified, i.e., does not start from `_root_`.
3. Added an unsafe `NewInstance` constructor similar to the safe one. 
```scala
NewInstance(tp: Type, argss: List[List[TermTree]])(implicit unsafe: Unsafe): TermTree
```
4. Migrated the existing uses of the old api.
> Def macros: Removed PathType

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
The separation of typed trees and untyped trees also protects user-code from being polluted.
> test to show hygiene for user-code

- macros/src/main/scala/gestalt/macros/DefMacros.scala
- macros/src/test/scala/gestalt/macros/DefMacroTest.scala
- src/main/scala/gestalt/api.scala
- src/main/scala/gestalt/core/Trees.scala
- src/main/scala/gestalt/dotty/DottyToolbox.scala
Previous implementation auto-updates owners when the typed constructors are used. However, it doesn't auto-update owners relative to the enclosing tree when `transform` is used. This PR reproduces the problem and proposes a fix.
> fix owner problem in typed transform
